version: 2.1

orbs:
  architect: giantswarm/architect@4.26.0

workflows:
  build:
    jobs:
    - architect/go-build:
        context: architect
        name: go-build
        binary: cluster-api-cleaner-openstack
        resource_class: xlarge
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-docker:
        context: architect
        name: push-cluster-api-cleaner-openstack-to-quay
        image: "quay.io/giantswarm/cluster-api-cleaner-openstack"
        username_envar: "QUAY_USERNAME"
        password_envar: "QUAY_PASSWORD"
        requires:
        - go-build
        filters:
          # Trigger the job also on git tag.
          tags:
            only: /^v.*/
    - architect/push-to-docker:
          context: "architect"
          name: push-cluster-api-cleaner-openstack-to-docker
          image: "docker.io/giantswarm/cluster-api-cleaner-openstack"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

    # Ensure that for every commit
    # there is an app version in the test catalog.
    - architect/push-to-app-catalog:
        context: architect
        name: push-to-app-catalog
        app_catalog: "control-plane-catalog"
        app_catalog_test: "control-plane-test-catalog"
        chart: "cluster-api-cleaner-openstack"
        requires:
        - push-cluster-api-cleaner-openstack-to-quay
        - push-cluster-api-cleaner-openstack-to-docker
        filters:
          # Trigger the job also on git tag.
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-openstack-app-collection
        app_name: "cluster-api-cleaner-openstack"
        app_collection_repo: "openstack-app-collection"
        requires:
        - push-to-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
